-- 코드를 입력하세요

SELECT PRODUCT_CODE, PRICE*TOTAL_AMOUNT AS SALES
FROM (
    SELECT O.PRODUCT_ID, O.SALES_AMOUNT, P.PRODUCT_CODE, P.PRICE, 
    SUM(O.SALES_AMOUNT) AS TOTAL_AMOUNT
    FROM OFFLINE_SALE O JOIN PRODUCT P USING(PRODUCT_ID)
    GROUP BY O.PRODUCT_ID
) T
ORDER BY PRICE*TOTAL_AMOUNT DESC, PRODUCT_CODE