-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(DISTINCT i.USER_ID) USERS
FROM USER_INFO as i,ONLINE_SALE as o
WHERE i.USER_ID = o.USER_ID AND GENDER is not null
GROUP BY 1,2,3
ORDER BY 1,2,3