-- 코드를 입력하세요

-- 코드를 입력하세요
SELECT CAR_ID, ROUND(SUM(DURATION) / COUNT(HISTORY_ID),1) AS AVERAGE_DURATION
FROM (
    SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE)+1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) AS NEW
GROUP BY CAR_ID
HAVING ROUND(SUM(DURATION) / COUNT(HISTORY_ID),1) >= 7.0
ORDER BY ROUND(SUM(DURATION) / COUNT(HISTORY_ID),1) DESC, CAR_ID DESC