-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, O.TOTAL_AMOUNT * P.PRICE TOTAL_SALES
FROM FOOD_PRODUCT AS P JOIN (
    SELECT PRODUCT_ID, SUM(AMOUNT) TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE "2022-05%"
    GROUP BY PRODUCT_ID
) O USING (PRODUCT_ID)
ORDER BY 3 DESC, 1