SELECT a.APNT_NO, PT_NAME, a.PT_NO, a.MCDP_CD, DR_NAME, a.APNT_YMD
FROM PATIENT as p ,DOCTOR as d, APPOINTMENT as a
WHERE a.MDDR_ID = d.DR_ID
AND a.PT_NO = p.PT_NO
AND a.MCDP_CD = "CS"
AND APNT_YMD like "2022-04-13%" 
AND APNT_CNCL_YN = "N"
ORDER BY APNT_YMD