-- 코드를 입력하세요
SELECT 
    USED_GOODS_USER.USER_ID, NICKNAME, TOTAL_SALES
FROM
    USED_GOODS_USER
INNER JOIN
    (SELECT 
        WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM
        USED_GOODS_BOARD
    WHERE
        STATUS = "DONE"
    GROUP BY 
        WRITER_ID
    HAVING
        TOTAL_SALES >= 700000
    ORDER BY
        TOTAL_SALES ASC
    ) AS B
ON
  USED_GOODS_USER.USER_ID = B.WRITER_ID