SELECT CONCAT("/home/grep/src/", F.BOARD_ID,"/", F.FILE_ID, F.FILE_NAME, F.FILE_EXT) as FILE_PATH
FROM USED_GOODS_FILE F JOIN (
    SELECT *
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
) B USING (BOARD_ID)
ORDER BY F.FILE_ID DESC
